<script lang="ts" setup name="HuaWeiStoreAudienceForm">
import {useVbenForm} from '@vben/common-ui';
import {$t} from '@vben/locales';
import {
  active_city_grade_dev,
  active_duration_dev,
  airfare_purch_dev,
  app_interest_v2_dev,
  app_type_actived_v2_dev,
  app_type_installed_v2_dev,
  apptype_usage_30d_duration_dev,
  apptype_usage_30d_times_dev,
  audio_entertainment_lovers_dev,
  book_tickets_pro_dev,
  business_service_job_hunting_dev,
  buy_house_flag_dev,
  buy_house_intention,
  buy_travel_agents_flag_dev,
  buy_trip_assistant_service_flag_dev,
  car_accessories_dev,
  car_brand_interest_owned_dev,
  car_brand_interest_potential_dev,
  car_decoration_dev,
  car_energy_interest_exist_dev,
  car_model_owned_dev,
  car_model_potential_dev,
  car_origin_interest_potential_dev,
  car_price_interest_exist_dev,
  car_price_interest_potential_dev,
  car_service_interest_dev,
  career_attributes_dev,
  career_third_level_type_dev,
  carowner_group,
  carrier_score_dev,
  children_books_dev,
  children_clothing_flag_dev,
  children_games_dev,
  children_video_audio_dev,
  city_new_dev,
  city_new_dev_dev,
  city_new_grade_dev,
  cleaner_dev,
  common_rent_house_flag_dev,
  communication_onlinerate_dev,
  comsumption_level,
  consume_ability_dev,
  consume_credit_card_level_dev,
  consume_frequency_dev,
  consume_game_level_dev,
  consume_level_dev,
  consume_purchase_dev,
  consume_spender_dev,
  cp_new_dev,
  credit_query_service_dev,
  cross_industry_exploration_dev,
  cur_emui_ver_num_dev,
  daily_installed_apps_dev,
  decorating_flag_dev,
  e_business_active_dev,
  e_business_feature_dev,
  edu_pay_dev,
  education_dev,
  female_clothes_buying_flag_dev,
  female_jacket_flag_dev,
  female_skirt_flag_dev,
  female_trousers_flag_dev,
  finance_accident_insurance_dev,
  finance_annuity_insurance_dev,
  finance_bank_interests_dev,
  finance_bond_dev,
  finance_bookkeeping_dev,
  finance_car_insurance_dev,
  finance_car_loan_dev,
  finance_creadit_card_interests_dev,
  finance_crowdfund_dev,
  finance_crude_dev,
  finance_digital_currency_dev,
  finance_financial_service_dev,
  finance_foreign_currency_dev,
  finance_fund_dev,
  finance_futures_dev,
  finance_house_loan_dev,
  finance_insurance_endowment_dev,
  finance_insurance_life_dev,
  finance_internet_bank_dev,
  finance_medical_insurance_dev,
  finance_microloans_dev,
  finance_overseas_asset_dev,
  finance_precious_metal_dev,
  finance_property_insurance_dev,
  finance_serious_illness_insurance_dev,
  finance_stock_dev,
  finance_trust_dev,
  finance_valued_client_dev,
  financial_bank_dev,
  financial_credit_card_apply_dev,
  financial_loan_apply_interests,
  financial_microloans_dev,
  financial_news_prefer,
  financial_risk_prefer,
  financial_securities_audiences,
  fitness_slimming_level,
  forecast_age_dev,
  game_30dy_app_new_install_cnt_dev,
  game_30dy_app_opened_cnt_dev,
  game_30dy_plat_usage_days_dev,
  game_booking_app_up,
  game_cancel_booking_dev,
  game_comic_game_degree_dev,
  game_cps_silence_days_dev,
  game_dlanum_30_dev,
  game_elements_dev,
  game_install_app_cnt_dev,
  game_ip_dev,
  game_level,
  game_payamout_30_dev,
  game_play_pref_dev,
  game_played_core_play_dev,
  game_played_game_play_dev,
  game_purchase_score,
  game_sdk_overall_silence_duration_up,
  game_study_machine_flag_dev,
  game_theme_dev,
  game_usage_app_cnt_dev,
  gender_new_dev,
  general_quality_audience_dev,
  health_interest_dev,
  high_consumption,
  high_end_clothing_luggage_flag_dev,
  high_speed_rail_dev,
  his_activated_apps_dev,
  his_installed_apps_dev,
  hispace_active_state_dev,
  hispace_app_install_pref_dev,
  hispace_expsoure_cnt,
  hispace_pay_user_cd_dev,
  hobby_game_carrier,
  hobby_game_theme,
  hobby_game_type,
  hobby_train_dev,
  home_appliances_maintain_dev,
  home_theater_purch_flag_dev,
  house_maintain_dev,
  house_move_dev,
  house_property_dev,
  incar_electrical_appliances_dev,
  insurance_dev_v1,
  int_asking_answers_community,
  int_audio_reader,
  int_blind_date,
  int_business,
  int_buy_new_car,
  int_buy_second_car,
  int_car_produce,
  int_city_making_friends,
  int_credit_card,
  int_curing_car,
  int_discount_shopping,
  int_ecommerce_platform,
  int_ecommerce_purchase,
  int_entertainment_live,
  int_fashion_brand,
  int_fashion_community,
  int_finance,
  int_game_artstyle,
  int_game_bhvr_carrier,
  int_game_bhvr_type,
  int_game_live,
  int_game_making_friends,
  int_game_play,
  int_game_purchase_fighting_landlord,
  int_game_purchase_fishing,
  int_game_purchase_mahjong,
  int_game_purchase_themes,
  int_high_net_worth,
  int_instant_message,
  int_internet_age_persion,
  int_loans,
  int_lower_tiered_city,
  int_luxury_brand,
  int_luxury_brand_car,
  int_make_strange_friends,
  int_militarynews_prefer,
  int_new_energy_car,
  int_news_prefer,
  int_personal_loan,
  int_prime_credit,
  int_purchase_3c_probability,
  int_purchase_clothes,
  int_purchase_drinks,
  int_purchase_food,
  int_purchase_home,
  int_purchase_luxury,
  int_purchase_overseas,
  int_purchase_pregnant_probability,
  int_purchase_wholesale,
  int_rent_car,
  int_video_chat,
  int_voice_make_friends,
  int_women_clothing,
  int_women_community,
  int_workplace_social,
  jnt_oprn_iap_30dy_pay_amt_up,
  juvenile_cohesion_dev,
  knowledge_payment_dev,
  language_train_dev,
  latest_province_dev,
  loan_probability,
  local_life_service_flag_dev,
  luxury_hotel_prefer,
  maintain_car_dev,
  marriage_status_dev,
  marry_love_friend_flag_dev,
  maternal_health_care_dev,
  maternity_matron_dev,
  menswear_flag_dev,
  mobile_entertainment_pref_dev,
  mother_baby_nursery_rhyme_score,
  mother_baby_services_score,
  motion_camera_buying_flag_dev,
  nanny_dev,
  network_v2_dev,
  new_house_transaction_flag_dev,
  ninetyd_app_active_dev,
  not_actived_seg_dev,
  novel_reading_perfer,
  online_shopping_flag_dev,
  ordinary_house_transaction_flag_dev,
  overseas_shopping_flag_dev,
  owner_cars_user_dev,
  owner_house_flag_dev,
  parenting_knowledge_dev,
  parenting_status_dev,
  pc_purch_flag_dev,
  pps_visit_city_one_month_dev,
  pps_visit_city_six_month_dev,
  pps_visit_city_three_month_dev,
  pps_visit_city_year_dev,
  pps_visit_country_one_month_dev,
  pps_visit_country_six_month_dev,
  pps_visit_country_three_month_dev,
  pps_visit_country_year_dev,
  price_new_dev,
  primary_secondary_edu_dev,
  probability_action_shooting_game_lovers_dev,
  probability_anime_lovers_dev,
  probability_board_game_lovers_dev,
  probability_business_strategy_game_lovers_dev,
  probability_card_payment_intention,
  probability_fishing_payment_intention,
  probability_immortal_xia_payment_intention,
  probability_legends_payment_intention,
  probability_live_broadcast_lovers_dev,
  probability_martial_arts_payment_intention,
  probability_music_interest_lovers_dev,
  probability_role_playing_game_lovers_dev,
  probability_role_playing_payment_intention,
  probability_sports_racing_game_lovers_dev,
  probability_strategy_payment_intention,
  probability_tower_defense_payment_intention,
  probability_video_new_user_payment_dev,
  product_new_dev,
  province_new_dev,
  purch_family_dev,
  purch_outeradv_dev,
  purch_sealeisure_dev,
  purch_seasonrec_dev,
  push_online_days_30d_dev,
  push_online_days_7d_dev,
  puz_game_lovers_dev,
  radio_dev,
  ram_dev,
  recent_trips_flag_dev,
  rent_house_intention,
  rent_shop_flag_dev,
  rent_villa_flag_dev,
  resolution_dev,
  school_district_house_transaction_flag_dev,
  second_house_transaction_flag_dev,
  second_third_score_dev,
  secondhand_trade_flag_dev,
  series_new_dev,
  short_video_lover_label,
  short_video_prefer,
  slr_camera_flag_dev,
  smartwatch_flag_dev,
  speaker_purch_flag_dev,
  sports_ball_games_dev,
  sports_culture_dev,
  sports_fitness_training_dev,
  sports_goods_dev,
  sports_interests_dev,
  sports_outdoor_extreme_dev,
  sports_running_riding_dev,
  sports_water_ice_dev,
  sportsnews_prefer,
  star_fan_adhesion_dev,
  subject_score_dev,
  switch_state_dev,
  tablet_purch_flag_dev,
  terminal_new_dev,
  thirtdy_app_active_dev,
  travel_lover_flag,
  up_realname_verify_dev,
  us_hours_30d_dev,
  user_education_intelligence,
  user_education_interest,
  user_education_language,
  user_watch_picbook,
  video_lover_label,
  vocation_interest_dev
} from './huawei_store_TagData';


const [Form, formApi] = useVbenForm({
  showDefaultActions: false,
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
    labelWidth: 120,
  },
  layout: 'horizontal',
  schema: [
    {
      component: 'Select',
      componentProps: {
        options: communication_onlinerate_dev,
        mode: 'multiple',
        showSearch: true,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'communication_onlinerate_dev',
      label: '手机在线时段',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: push_online_days_30d_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'push_online_days_30d_dev',
      label: '手机月在线天数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: push_online_days_7d_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'push_online_days_7d_dev',
      label: '手机周在线天数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: forecast_age_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'forecast_age_dev',
      label: '年龄',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: terminal_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'terminal_new_dev',
      label: '外部型号',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: series_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'series_new_dev',
      label: '手机系列',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: price_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'price_new_dev',
      label: '价格',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: gender_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'gender_new_dev',
      label: '性别',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_payamout_30_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_payamout_30_dev',
      label: '近30天网游支付金额',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: product_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'product_new_dev',
      label: '产品',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_dlanum_30_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_dlanum_30_dev',
      label: '近30天下载游戏个数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: his_activated_apps_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'his_activated_apps_dev',
      label: '曾经使用过的APP',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: daily_installed_apps_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'daily_installed_apps_dev',
      label: '每日安装应用',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: his_installed_apps_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'his_installed_apps_dev',
      label: '历史安装应用',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hispace_active_state_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hispace_active_state_dev',
      label: '应用市场最近活跃距今天数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: thirtdy_app_active_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'thirtdy_app_active_dev',
      label: '第三方APP活跃',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: app_type_actived_v2_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'app_type_actived_v2_dev',
      label: '活跃应用类别',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hispace_app_install_pref_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hispace_app_install_pref_dev',
      label: '安装应用类别偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hispace_pay_user_cd_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hispace_pay_user_cd_dev',
      label: '是否应用市场付费用户',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: latest_province_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'latest_province_dev',
      label: '地址信息',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: city_new_dev_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'city_new_dev_dev',
      label: '城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: active_city_grade_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'active_city_grade_dev',
      label: '城市等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_elements_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_elements_dev',
      label: '玩过的游戏元素',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_ip_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_ip_dev',
      label: '游戏IP',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_theme_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_theme_dev',
      label: '游戏主题',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_played_game_play_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_played_game_play_dev',
      label: '玩过的游戏玩法',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_played_core_play_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_played_core_play_dev',
      label: '玩过的核心玩法',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_sdk_overall_silence_duration_up,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_sdk_overall_silence_duration_up',
      label: '游戏整体沉默时长',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_cancel_booking_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_cancel_booking_dev',
      label: '取消预约游戏',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_cps_silence_days_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_cps_silence_days_dev',
      label: '游戏沉默天数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_comic_game_degree_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_comic_game_degree_dev',
      label: '二次元游戏程度',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_30dy_plat_usage_days_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_30dy_plat_usage_days_dev',
      label: '近30天竞品游戏平台使用天数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_booking_app_up,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_booking_app_up',
      label: '已预约的游戏',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_30dy_app_new_install_cnt_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_30dy_app_new_install_cnt',
      label: '30天内新安装游戏个数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_30dy_app_opened_cnt_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_30dy_app_opened_cnt',
      label: '30天内打开过游戏个数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_install_app_cnt_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_install_app_cnt',
      label: '当前安装游戏个数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_usage_app_cnt_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_usage_app_cnt',
      label: '曾打开过游戏个数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: ninetyd_app_active_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'nined_app_active',
      label: '90天内使用过的APP',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_purchase_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_purchase_dev',
      label: '是否剁手党',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_spender_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_spender_dev',
      label: '消费水平',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: mobile_entertainment_pref_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'mobile_entertainment_pref_dev',
      label: '手机娱乐偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: app_type_installed_v2_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'app_type_installed_v2_dev',
      label: '已安装APP分类',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: jnt_oprn_iap_30dy_pay_amt_up,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'jnt_oprn_iap_30dy_pay_amt_up',
      label: '游戏累计支付金额',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: travel_lover_flag,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'travel_lover_flag',
      label: '是否旅游爱好者',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: not_actived_seg_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'not_actived_seg_dev',
      label: 'APP当前安装未活跃',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_play_pref_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_play_pref_dev',
      label: '游戏属性偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: active_duration_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'active_duration_dev',
      label: '开机天数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: carrier_score_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'carrier_score_dev',
      label: '移动运营商',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: cp_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'cp_new_dev',
      label: 'CP',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: us_hours_30d_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'us_hours_30d_dev',
      label: '使用时长',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: city_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'city_new_dev',
      label: '城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: switch_state_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'switch_state_dev',
      label: '开关状态',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: resolution_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'resolution_dev',
      label: '分辨率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: ram_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'ram_dev',
      label: '内存',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_card_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_card_payment_intention',
      label: '卡牌付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_video_new_user_payment_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_video_new_user_payment_dev',
      label: '视频新用户付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_tower_defense_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_tower_defense_payment_intention',
      label: '塔防付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_strategy_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_strategy_payment_intention',
      label: '策略付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_role_playing_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_role_playing_payment_intention',
      label: '角色扮演付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_martial_arts_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_martial_arts_payment_intention',
      label: '武侠付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_legends_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_legends_payment_intention',
      label: '传奇付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_immortal_xia_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_immortal_xia_payment_intention',
      label: '仙侠付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_fishing_payment_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_fishing_payment_intention',
      label: '钓鱼付费意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_loan_apply_interests,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_loan_apply_interests',
      label: '金融贷款申请意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: cur_emui_ver_num_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'cur_emui_ver_num_dev',
      label: '当前EMUI版本号',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: star_fan_adhesion_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'star_fan_adhesion_dev',
      label: '星粉粘性',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_ecommerce_purchase,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_ecommerce_purchase',
      label: '电商购买意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_lower_tiered_city,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_lower_tiered_city',
      label: '低线城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_ecommerce_platform,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_ecommerce_platform',
      label: '电商平台',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_high_net_worth,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_high_net_worth',
      label: '高净值',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_internet_age_persion,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_internet_age_persion',
      label: '互联网年龄',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_artstyle,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_artstyle',
      label: '游戏美术风格',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_luxury,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_luxury',
      label: '奢侈品购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_purchase_fighting_landlord,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_purchase_fighting_landlord',
      label: '游戏购买斗地主',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_purchase_mahjong,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_purchase_mahjong',
      label: '游戏购买麻将',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_purchase_fishing,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_purchase_fishing',
      label: '游戏购买钓鱼',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_instant_message,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_instant_message',
      label: '即时通讯',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_asking_answers_community,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_asking_answers_community',
      label: '问答社区',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: career_attributes_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'career_attributes_dev',
      label: '职业属性',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_play,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_play',
      label: '游戏玩法',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_making_friends,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_making_friends',
      label: '游戏交友',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_video_chat,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_video_chat',
      label: '视频聊天',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_fashion_brand,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_fashion_brand',
      label: '时尚品牌',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_clothes,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_clothes',
      label: '服装购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_purchase_themes,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_purchase_themes',
      label: '游戏购买主题',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_overseas,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_overseas',
      label: '海外购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_wholesale,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_wholesale',
      label: '批发购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_home,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_home',
      label: '家居购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_voice_make_friends,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_voice_make_friends',
      label: '语音交友',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_women_community,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_women_community',
      label: '女性社区',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_city_making_friends,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_city_making_friends',
      label: '同城交友',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_workplace_social,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_workplace_social',
      label: '职场社交',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_fashion_community,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_fashion_community',
      label: '时尚社区',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_women_clothing,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_women_clothing',
      label: '女装',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_discount_shopping,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_discount_shopping',
      label: '折扣购物',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_food,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_food',
      label: '食品购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_drinks,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_drinks',
      label: '饮品购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_blind_date,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_blind_date',
      label: '相亲',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_luxury_brand_car,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_luxury_brand_car',
      label: '豪华品牌汽车',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hobby_game_type,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hobby_game_type',
      label: '游戏类型爱好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hobby_game_theme,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hobby_game_theme',
      label: '游戏主题爱好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hobby_game_carrier,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hobby_game_carrier',
      label: '游戏载体爱好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_new_energy_car,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_new_energy_car',
      label: '新能源汽车',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_loans,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_loans',
      label: '贷款',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_bhvr_type,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_bhvr_type',
      label: '游戏行为类型',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_bhvr_carrier,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_bhvr_carrier',
      label: '游戏行为载体',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_finance,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_finance',
      label: '金融',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_curing_car,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_curing_car',
      label: '汽车治疗',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_luxury_brand,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_luxury_brand',
      label: '奢侈品牌',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_car_produce,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_car_produce',
      label: '汽车生产',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_game_level_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_game_level_dev',
      label: '游戏消费等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_level_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_level_dev',
      label: '消费等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: career_third_level_type_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'career_third_level_type_dev',
      label: '职业三级类型',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: short_video_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'short_video_prefer',
      label: '短视频偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: carowner_group,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'carowner_group',
      label: '车主群体',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_business,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_business',
      label: '商务',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_rent_car,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_rent_car',
      label: '租车',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_pregnant_probability,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_pregnant_probability',
      label: '怀孕购买概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_purchase_3c_probability,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_purchase_3c_probability',
      label: '3C购买概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_prime_credit,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_prime_credit',
      label: '优质信用',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_personal_loan,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_personal_loan',
      label: '个人贷款',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_militarynews_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_militarynews_prefer',
      label: '军事新闻偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_make_strange_friends,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_make_strange_friends',
      label: '交友',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_game_live,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_game_live',
      label: '游戏直播',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_entertainment_live,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_entertainment_live',
      label: '娱乐直播',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_credit_card,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_credit_card',
      label: '信用卡',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: credit_query_service_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'credit_query_service_dev',
      label: '信用查询服务',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: incar_electrical_appliances_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'incar_electrical_appliances_dev',
      label: '车载电器',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_accessories_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_accessories_dev',
      label: '汽车配件',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_decoration_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_decoration_dev',
      label: '汽车装饰',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_buy_second_car,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_buy_second_car',
      label: '购买二手车',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_buy_new_car,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_buy_new_car',
      label: '购买新车',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_news_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_news_prefer',
      label: '新闻偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: int_audio_reader,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'int_audio_reader',
      label: '音频阅读',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: up_realname_verify_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'up_realname_verify_dev',
      label: '实名认证',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: loan_probability,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'loan_probability',
      label: '贷款概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: comsumption_level,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'comsumption_level',
      label: '消费水平',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_news_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_news_prefer',
      label: '金融新闻偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sportsnews_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sportsnews_prefer',
      label: '体育新闻偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: novel_reading_perfer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'novel_reading_perfer',
      label: '小说阅读偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: education_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'education_dev',
      label: '教育',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: user_watch_picbook,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'user_watch_picbook',
      label: '观看图册',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: fitness_slimming_level,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'fitness_slimming_level',
      label: '健身减肥等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: user_education_language,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'user_education_language',
      label: '用户教育语言',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: user_education_intelligence,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'user_education_intelligence',
      label: '用户教育智力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: user_education_interest,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'user_education_interest',
      label: '用户教育兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_level,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_level',
      label: '游戏等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_purchase_score,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_purchase_score',
      label: '游戏购买评分',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: rent_house_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'rent_house_intention',
      label: '租房意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: buy_house_intention,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'buy_house_intention',
      label: '购房意向',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: cross_industry_exploration_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'cross_industry_exploration_dev',
      label: '跨行业探索',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: e_business_feature_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'e_business_feature_dev',
      label: '电商特征',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: general_quality_audience_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'general_quality_audience_dev',
      label: '一般质量受众',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: e_business_active_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'e_business_active_dev',
      label: '电商活跃',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hispace_expsoure_cnt,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hispace_expsoure_cnt',
      label: '应用市场曝光次数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: health_interest_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'health_interest_dev',
      label: '健康兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: owner_cars_user_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'owner_cars_user_dev',
      label: '车主用户',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_frequency_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_frequency_dev',
      label: '消费频率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_risk_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_risk_prefer',
      label: '金融风险偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_securities_audiences,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_securities_audiences',
      label: '金融证券受众',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: luxury_hotel_prefer,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'luxury_hotel_prefer',
      label: '豪华酒店偏好',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: radio_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'radio_dev',
      label: '收音机',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_ability_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_ability_dev',
      label: '消费能力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: primary_secondary_edu_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'primary_secondary_edu_dev',
      label: '中小学教育',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: edu_pay_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'edu_pay_dev',
      label: '教育付费',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: mother_baby_nursery_rhyme_score,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'mother_baby_nursery_rhyme_score',
      label: '母婴儿歌评分',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: local_life_service_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'local_life_service_flag_dev',
      label: '本地生活服务',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: mother_baby_services_score,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'mother_baby_services_score',
      label: '母婴服务评分',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: parenting_status_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'parenting_status_dev',
      label: '育儿状态',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: marriage_status_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'marriage_status_dev',
      label: '婚姻状态',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: consume_credit_card_level_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'consume_credit_card_level_dev',
      label: '消费信用卡等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_energy_interest_exist_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_energy_interest_exist_dev',
      label: '汽车能源兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_price_interest_exist_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_price_interest_exist_dev',
      label: '汽车价格兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_origin_interest_potential_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_origin_interest_potential_dev',
      label: '汽车产地兴趣潜力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_price_interest_potential_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_price_interest_potential_dev',
      label: '汽车价格兴趣潜力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_model_potential_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_model_potential_dev',
      label: '汽车车型潜力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_model_owned_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_model_owned_dev',
      label: '汽车车型拥有',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_brand_interest_potential_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_brand_interest_potential_dev',
      label: '汽车品牌兴趣潜力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_brand_interest_owned_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_brand_interest_owned_dev',
      label: '汽车品牌兴趣拥有',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: parenting_knowledge_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'parenting_knowledge_dev',
      label: '育儿知识',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: children_video_audio_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'children_video_audio_dev',
      label: '儿童视频音频',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: children_games_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'children_games_dev',
      label: '儿童游戏',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: children_books_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'children_books_dev',
      label: '儿童书籍',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: business_service_job_hunting_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'business_service_job_hunting_dev',
      label: '商务服务求职',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: knowledge_payment_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'knowledge_payment_dev',
      label: '知识付费',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: children_clothing_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'children_clothing_flag_dev',
      label: '童装',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: maternal_health_care_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'maternal_health_care_dev',
      label: '孕产保健',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: owner_house_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'owner_house_flag_dev',
      label: '业主房屋',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_valued_client_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_valued_client_dev',
      label: '金融高价值客户',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_trust_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_trust_dev',
      label: '金融信托',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_overseas_asset_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_overseas_asset_dev',
      label: '金融海外资产',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_precious_metal_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_precious_metal_dev',
      label: '金融贵金属',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_crude_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_crude_dev',
      label: '金融原油',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_futures_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_futures_dev',
      label: '金融期货',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_serious_illness_insurance_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_serious_illness_insurance_dev',
      label: '金融重疾保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_medical_insurance_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_medical_insurance_dev',
      label: '金融医疗保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_annuity_insurance_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_annuity_insurance_dev',
      label: '金融年金保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_accident_insurance_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_accident_insurance_dev',
      label: '金融意外保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_bond_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_bond_dev',
      label: '金融债券',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_foreign_currency_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_foreign_currency_dev',
      label: '金融外汇',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_car_loan_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_car_loan_dev',
      label: '金融汽车贷款',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_house_loan_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_house_loan_dev',
      label: '金融房屋贷款',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_goods_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_goods_dev',
      label: '体育用品',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_culture_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_culture_dev',
      label: '体育文化',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_fitness_training_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_fitness_training_dev',
      label: '体育健身训练',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_outdoor_extreme_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_outdoor_extreme_dev',
      label: '体育户外极限',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_water_ice_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_water_ice_dev',
      label: '体育水上冰上',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_running_riding_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_running_riding_dev',
      label: '体育骑行跑步',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_ball_games_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_ball_games_dev',
      label: '体育球类',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: buy_trip_assistant_service_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'buy_trip_assistant_service_flag_dev',
      label: '购买出行助理服务',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: overseas_shopping_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'overseas_shopping_flag_dev',
      label: '海外购物',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_creadit_card_interests_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_creadit_card_interests_dev',
      label: '金融信用卡兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_bank_interests_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_bank_interests_dev',
      label: '金融银行兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_crowdfund_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_crowdfund_dev',
      label: '金融众筹',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_internet_bank_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_internet_bank_dev',
      label: '金融互联网银行',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_bookkeeping_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_bookkeeping_dev',
      label: '金融记账',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_financial_service_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_financial_service_dev',
      label: '金融服务',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_digital_currency_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_digital_currency_dev',
      label: '金融数字货币',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_microloans_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_microloans_dev',
      label: '金融小额贷款',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: purch_seasonrec_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'purch_seasonrec_dev',
      label: '购买季节推荐',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: purch_sealeisure_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'purch_sealeisure_dev',
      label: '购买海上休闲',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_car_insurance_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_car_insurance_dev',
      label: '金融汽车保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_insurance_endowment_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_insurance_endowment_dev',
      label: '金融养老保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_insurance_life_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_insurance_life_dev',
      label: '金融人寿保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_property_insurance_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_property_insurance_dev',
      label: '金融财产保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: book_tickets_pro_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'book_tickets_pro_dev',
      label: '预订机票专业版',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: buy_travel_agents_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'buy_travel_agents_flag_dev',
      label: '购买旅行社服务',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: sports_interests_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'sports_interests_dev',
      label: '体育兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: purch_outeradv_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'purch_outeradv_dev',
      label: '购买户外广告',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: female_skirt_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'female_skirt_flag_dev',
      label: '女性裙子',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: female_trousers_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'female_trousers_flag_dev',
      label: '女性裤子',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: female_jacket_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'female_jacket_flag_dev',
      label: '女性夹克',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: airfare_purch_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'airfare_purch_dev',
      label: '机票购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: purch_family_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'purch_family_dev',
      label: '家庭购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: high_speed_rail_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'high_speed_rail_dev',
      label: '高铁',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_anime_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_anime_lovers_dev',
      label: '动漫爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: home_theater_purch_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'home_theater_purch_flag_dev',
      label: '家庭影院购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: speaker_purch_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'speaker_purch_flag_dev',
      label: '音箱购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pc_purch_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pc_purch_flag_dev',
      label: '电脑购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: game_study_machine_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'game_study_machine_flag_dev',
      label: '游戏学习机',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: rent_shop_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'rent_shop_flag_dev',
      label: '租店',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: common_rent_house_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'common_rent_house_flag_dev',
      label: '普通租房',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: rent_villa_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'rent_villa_flag_dev',
      label: '租别墅',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: high_end_clothing_luggage_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'high_end_clothing_luggage_flag_dev',
      label: '高端服装箱包',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: nanny_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'nanny_dev',
      label: '保姆',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: maternity_matron_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'maternity_matron_dev',
      label: '月嫂',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: house_move_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'house_move_dev',
      label: '搬家',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: house_maintain_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'house_maintain_dev',
      label: '房屋维修',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: home_appliances_maintain_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'home_appliances_maintain_dev',
      label: '家电维修',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: cleaner_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'cleaner_dev',
      label: '清洁工',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: marry_love_friend_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'marry_love_friend_flag_dev',
      label: '婚恋交友',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: secondhand_trade_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'secondhand_trade_flag_dev',
      label: '二手交易',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: recent_trips_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'recent_trips_flag_dev',
      label: '近期出行',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_stock_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_stock_dev',
      label: '金融股票',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: finance_fund_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'finance_fund_dev',
      label: '金融基金',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: insurance_dev_v1,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'insurance_dev_v1',
      label: '保险',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_bank_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_bank_dev',
      label: '金融银行',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: motion_camera_buying_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'motion_camera_buying_flag_dev',
      label: '运动相机购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: second_house_transaction_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'second_house_transaction_flag_dev',
      label: '二手房交易',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: new_house_transaction_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'new_house_transaction_flag_dev',
      label: '新房交易',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: school_district_house_transaction_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'school_district_house_transaction_flag_dev',
      label: '学区房交易',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: smartwatch_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'smartwatch_flag_dev',
      label: '智能手表',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: buy_house_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'buy_house_flag_dev',
      label: '购房',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: tablet_purch_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'tablet_purch_flag_dev',
      label: '平板购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: menswear_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'menswear_flag_dev',
      label: '男装',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: ordinary_house_transaction_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'ordinary_house_transaction_flag_dev',
      label: '普通房屋交易',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: slr_camera_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'slr_camera_flag_dev',
      label: '单反相机',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: car_service_interest_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'car_service_interest_dev',
      label: '汽车服务兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_microloans_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_microloans_dev',
      label: '金融小额贷款',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_role_playing_game_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_role_playing_game_lovers_dev',
      label: '角色扮演游戏爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_business_strategy_game_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_business_strategy_game_lovers_dev',
      label: '商业策略游戏爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_board_game_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_board_game_lovers_dev',
      label: '桌游爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: apptype_usage_30d_duration_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'apptype_usage_30d_duration_dev',
      label: '应用类型30天使用时长',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: apptype_usage_30d_times_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'apptype_usage_30d_times_dev',
      label: '应用类型30天使用次数',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: female_clothes_buying_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'female_clothes_buying_flag_dev',
      label: '女装购买',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: puz_game_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'puz_game_lovers_dev',
      label: '益智游戏爱好者',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: audio_entertainment_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'audio_entertainment_lovers_dev',
      label: '音频娱乐爱好者',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: juvenile_cohesion_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'juvenile_cohesion_dev',
      label: '青少年凝聚力',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: house_property_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'house_property_dev',
      label: '房产',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: financial_credit_card_apply_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'financial_credit_card_apply_dev',
      label: '金融信用卡申请',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: second_third_score_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'second_third_score_dev',
      label: '第二第三评分',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_music_interest_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_music_interest_lovers_dev',
      label: '音乐兴趣爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_live_broadcast_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_live_broadcast_lovers_dev',
      label: '直播爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_action_shooting_game_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_action_shooting_game_lovers_dev',
      label: '动作射击游戏爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: probability_sports_racing_game_lovers_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'probability_sports_racing_game_lovers_dev',
      label: '体育竞速游戏爱好者概率',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: subject_score_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'subject_score_dev',
      label: '学科评分',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: language_train_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'language_train_dev',
      label: '语言培训',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: vocation_interest_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'vocation_interest_dev',
      label: '职业兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: hobby_train_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'hobby_train_dev',
      label: '爱好培训',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: maintain_car_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'maintain_car_dev',
      label: '汽车保养',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: decorating_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'decorating_flag_dev',
      label: '装修',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: video_lover_label,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'video_lover_label',
      label: '视频爱好者标签',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: short_video_lover_label,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'short_video_lover_label',
      label: '短视频爱好者标签',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: online_shopping_flag_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'online_shopping_flag_dev',
      label: '网购',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: high_consumption,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'high_consumption',
      label: '高消费',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_country_year_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_country_year_dev',
      label: '年访问国家',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_country_six_month_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_country_six_month_dev',
      label: '半年访问国家',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_country_three_month_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_country_three_month_dev',
      label: '三个月访问国家',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_country_one_month_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_country_one_month_dev',
      label: '一个月访问国家',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_city_year_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_city_year_dev',
      label: '年访问城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_city_six_month_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_city_six_month_dev',
      label: '半年访问城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_city_three_month_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_city_three_month_dev',
      label: '三个月访问城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: pps_visit_city_one_month_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'pps_visit_city_one_month_dev',
      label: '一个月访问城市',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: city_new_grade_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'city_new_grade_dev',
      label: '城市等级',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: network_v2_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'network_v2_dev',
      label: '网络',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: app_interest_v2_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'app_interest_v2_dev',
      label: '应用兴趣',
    },
    {
      component: 'Select',
      componentProps: {
        mode: 'multiple',
        showSearch: true,
        options: province_new_dev,
        placeholder: `${$t('common.select')}`,
      },
      fieldName: 'province_new_dev',
      label: '省份',
    },
  ]
});

// 提交表单数据
async function submitHuaweiStoreConfig() {
  const formValue = await formApi.getValues();
  return formValue;
}

// 回显数据
async function echoHuaweiStoreConfig(data: any) {
  if (data.config) {
    formApi.setValues(data.config);
  }
}

// 取消表单
async function popUpCancel() {
  await formApi.resetForm();
}

defineExpose({
  submitHuaweiStoreConfig,
  echoHuaweiStoreConfig,
  popUpCancel,
});
</script>

<template>
  <div>
    <Form/>
  </div>
</template>

<style lang="less" scoped>
</style>
