/**
 * 巨量智擎版枚举定义
 *
 * 智擎版是单层结构（只有项目层级），复用现有巨量引擎枚举
 * 统一模板：std_project_template
 */

// ==================== 模板类型 ====================
export const BYTEDANCE_STD_MARKETING_TYPE = [
  {
    label: '智擎标准项目',
    value: 'base_template',
  },
  {
    label: 'App推广模板',
    value: 'app_template',
  },
];

// ==================== 从巨量引擎复用枚举 ====================
export {
  CampaignOperation,
  DeliveryMode,
  BytedanceCampaign_landing_type,
  BytedanceCampaign_app_promotion_type,
  BytedanceCampaign_marketing_goal,
  BytedanceCampaign_ad_type,
  BytedanceCampaign_delivery_type,
  BytedanceCampaign_aigc_dynamic_creative_switch,
  BytedanceCampaign_star_auto_material_addition_switch,
  BytedanceCampaign_star_auto_delivery_switch,
  BytedanceCampaign_audience_extend,
  BytedanceCampaign_auto_extend_traffic,
  BytedanceCampaign_keyword_bid_type,
  BytedanceCampaign_keyword_match_type,
  BytedanceCampaign_blue_flow_package_setting,
  BytedanceCampaign_product_setting,
  BytedanceCampaign_download_mode,
  BytedanceCampaign_download_type,
  BytedanceCampaign_launch_type,
  BytedanceCampaign_promotion_type,
  BytedanceCampaign_open_url_type,
  BytedanceCampaign_ulink_url_type,
  BytedanceCampaign_asset_type,
  BytedanceCampaign_multi_asset_type,
  BytedanceCampaign_micro_promotion_type,
  BytedanceCampaign_dpa_adtype,
  BytedanceCampaign_paid_switch,
  BytedanceCampaign_value_optimized_type,
  BytedanceCampaign_landing_page_stay_time,
  BytedanceCampaign_inventory_catalog,
  BytedanceCampaign_inventory_type,
  BytedanceCampaign_union_video_type,
  BytedanceCampaign_schedule_type,
  BytedanceCampaign_filter_night_switch,
  BytedanceCampaign_deep_bid_type,
  BytedanceCampaign_bid_type,
  BytedanceCampaign_project_custom,
  BytedanceCampgin_budget_mode,
  BytedanceCampaign_pricing,
  BytedanceCampaign_layer_roi_switch,
  BytedanceCampaign_budget_optimize_switch,
  BytedanceCampaign_search_continue_delivery,
  BytedanceCampaign_send_type,
  BytedancePromotion_anchor_related_type,
  BytedancePromotion_intelligent_generation,
  BytedancePromotion_is_comment_disable,
  BytedancePromotion_ad_download_status,
  BytedancePromotion_budget_mode,
  BytedancePromotion_shop_platform,
  BytedancePromotion_auto_extend_traffic,
  BytedancePromotion_match_type,
  BytedanceCampaign_external_action,
  // Label helper functions
  getLandingTypeLabel,
  getAppPromotionTypeLabel,
  getMarketingGoalLabel,
  getAdTypeLabel,
  getDeliveryTypeLabel,
  getAigcDynamicCreativeSwitchLabel,
  getStarAutoMaterialAdditionSwitchLabel,
  getStarAutoDeliverySwitchLabel,
  getAudienceExtendLabel,
  getAutoExtendTrafficCampaignLabel,
  getKeywordBidTypeLabel,
  getKeywordMatchTypeLabel,
  getBlueFlowPackageSettingLabel,
  getProductSettingLabel,
  getDownloadModeLabel,
  getDownloadTypeLabel,
  getLaunchTypeLabel,
  getPromotionTypeLabel,
  getOpenUrlTypeLabel,
  getUlinkUrlTypeLabel,
  getAssetTypeLabel,
  getMultiAssetTypeLabel,
  getMicroPromotionTypeLabel,
  getDpaAdtypeLabel,
  getPaidSwitchLabel,
  getValueOptimizedTypeLabel,
  getLandingPageStayTimeLabel,
  getInventoryCatalogLabel,
  getInventoryTypeLabel,
  getUnionVideoTypeLabel,
  getScheduleTypeLabel,
  getFilterNightSwitchLabel,
  getDeepBidTypeLabel,
  getBidTypeLabel,
  getProjectCustomLabel,
  getBudgetModeCampaignLabel,
  getPricingLabel,
  getLayerRoiSwitchLabel,
  getBudgetOptimizeSwitchLabel,
  getSearchContinueDeliveryLabel,
  getSendTypeLabel,
  getAnchorRelatedTypeLabel,
  getIntelligentGenerationLabel,
  getIsCommentDisableLabel,
  getAdDownloadStatusLabel,
  getBudgetModePromotionLabel,
  getShopPlatformLabel,
  getAutoExtendTrafficPromotionLabel,
  getMatchTypeLabel,
  getExternalActionLabel,
  getCampaignOperationLabel,
  getDeliveryModeLabel,
  fieldLabelMap,
} from '#/views/marketing/creation/bytedance/enums';



export const BytedanceNativeType = [
  {
    label: '账户信息',
    value: 'ACCOUNT'
  },
  {
    label: '抖音号',
    value: 'AWEME'
  },
]
